name: Compile Release

on: 
  release:
    types: [created]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Build
      run: cargo build --release
    - name: Create Release Zip
      run: |
        cp target/release/libsm4sh_model_py.so sm4sh_blender/sm4sh_model_py.so
        zip -r sm4sh_blender_linux_x64.zip sm4sh_blender
    - name: Upload Zip
      uses: actions/upload-artifact@v4
      with:
        name: sm4sh_blender_linux
        path: sm4sh_blender_linux_x64.zip
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: sm4sh_blender_linux_x64.zip
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Build
      run: cargo build --release
    - name: Create Release Zip
      run: |
        cp target/release/sm4sh_model_py.dll sm4sh_blender/sm4sh_model_py.pyd
        Compress-Archive -path sm4sh_blender -destinationPath sm4sh_blender_win_x64.zip 
    - name: Upload Zip
      uses: actions/upload-artifact@v4
      with:
        name: sm4sh_blender_win
        path: sm4sh_blender_win_x64.zip
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: sm4sh_blender_win_x64.zip
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin]
        desc: [intel]
        include:
          - target: aarch64-apple-darwin
            desc: apple_silicon
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install maturin
      run: |
        python -m pip install --upgrade pip
        pip install maturin
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{matrix.target}}
    - name: Build
      run: |
        cd sm4sh_model_py
        maturin build --release --target=${{matrix.target}}
        cd ../..
    - name: Create Release Zip
      run: |
        cp target/${{matrix.target}}/release/libsm4sh_model_py.dylib sm4sh_blender/sm4sh_model_py.so
        zip -r sm4sh_blender_macos_${{matrix.desc}}.zip sm4sh_blender
    - name: Upload Zip
      uses: actions/upload-artifact@v4
      with:
        name: sm4sh_blender_macos_${{matrix.desc}}
        path: sm4sh_blender_macos_${{matrix.desc}}.zip
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: sm4sh_blender_macos_${{matrix.desc}}.zip
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
